---
- name: Install UEFI OVMF files
  yum:
    name: https://www.kraxel.org/repos/jenkins/edk2/edk2.git-ovmf-x64-0-20220719.209.gf0064ac3af.EOL.no.nore.updates.noarch.rpm
    state: present
  become_user: root
  become: true
  when:
    - (ansible_distribution_major_version|int == 8 and ansible_architecture in ['x86_64'])
