---

- name: Make sure required packages are installed
  dnf:
    name: "{{ packages }}"
    state: present
  become_user: root
  become: true
  vars:
    packages:
      - @virtualization-tools
      - @virtualization-platform
      - @virtualization-hypervisor
      - epel-release

- name: Install ansible
  dnf:
    name: "{{ packages }}"
    state: present
    enablerepo: epel
  become_user: root
  become: true
  vars:
    packages:
      - ansible
      - unzip

- name: Download packer
  get_url:
    url: "https://releases.hashicorp.com/packer/1.7.10/packer_1.7.10_linux_ppc64le.zip"
    dest: /tmp
    mode: 0644

- name: Unzip packer
  shell: sudo unzip -o packer_1.7.10_linux_ppc64le.zip -d /usr/bin/

- name: Install packer
  shell: sudo ln -s /usr/bin/packer /usr/bin/packer.io
